Updated some stuff to avoid crash
On my system the website gave the following error on `yarn serve`:

    Error: error:0308010C:digital envelope routines::unsupported

Updating the dependencies has resolved it for me. I tried to avoid
dropping support for NodeJS 12, since our server runs
12.22.12-1nodesource1 according to Freeyorp.

* vuejs/eslint-config-typescript 9.0.0 drops support for
  Node.js < v12.22.0, v13, >=v14 < v14.17.0, v15

* typescript-eslint/eslint-plugin 6.0.0 drops support for Node.js v12
  and v14.

* compression-webpack-plugin 10.0.0 would require Node.js 14.15.0